### ISSUE TITLE
Request to adding the attachments of Location 

### ISSUE THREAD

**Issue by chithramanikalimuthu** [Savitha2662/Eclipse_Development#3]
Dear Girl,

It would be great if Your application having the sharing locations. Kindly add this features.
`void vovels() {
		String name="ChithRAmaNIkalimuthu";
		name=name.toLowerCase();
		int count=0;
		for(int i=0;i<name.length();i++) {
			char countings=name.charAt(i);
			if(countings=='a' || countings=='e' || countings=='i' || countings=='o' || countings=='u') {
				count++;
			}
		}
		System.out.println(count);

}
[DEEPI.pdf](https://github.com/Savitha2662/Eclipse_Development/files/13691730/DEEPI.pdf)
 #@Savitha
	`

**Comment by Savitha2662** [comment]
Dear Chittu,

       This is a nice feature, I will attach this feature and let u know

**Comment by Savitha2662** [comment]
Dear Chittu,

  Its a great idea and feature, I Successfully added this feature. Thank you and keep supporting.
